/**
 * Tweak catalog — categories, risk badges and whitelist command *types*.
 * Benchmarked against Sparkle / WinUtil categories, not copied from their code.
 *
 * command.type is the only thing the executor accepts (whitelist).
 */

export const CATEGORIES = Object.freeze({
  standard: {
    id: 'standard',
    name: 'Padrão',
    risk: 'low',
    badge: 'Padrão',
    description: 'Baixo risco, recomendado a todos os tiers. Sempre reversível.',
  },
  advanced: {
    id: 'advanced',
    name: 'Avançado',
    risk: 'high',
    badge: 'Avançado',
    description: 'Requer confirmação explícita. Alguns itens só são sugeridos em PC Potente.',
  },
  privacy: {
    id: 'privacy',
    name: 'Privacidade',
    risk: 'low',
    badge: 'Privacidade',
    description: 'Opt-in, reversível item a item. Estado lido do snapshot da app + probes do sistema.',
  },
  debloat: {
    id: 'debloat',
    name: 'Debloat',
    risk: 'medium',
    badge: 'Debloat',
    description: 'Remove apps UWP não essenciais. Apps essenciais nunca entram nesta lista.',
  },
})

export const TWEAKS = [
  // ——— Padrão ———
  {
    id: 'visual-effects',
    name: 'Reduzir animações e efeitos visuais',
    description: 'Desliga animações supérfluas do Explorer e da UI para libertar GPU/CPU em PCs fracos.',
    category: 'standard',
    risk: 'low',
    reversible: true,
    command: { type: 'registry', hive: 'HKCU', path: 'Software\\HLOptimizer\\VisualEffects', value: 'Off' },
    revertCommand: { type: 'registry', hive: 'HKCU', path: 'Software\\HLOptimizer\\VisualEffects', value: 'On' },
  },
  {
    id: 'power-plan',
    name: 'Ajustar plano de energia',
    description: 'Aplica o plano adequado ao modo ativo. Ultimate Performance só é oferecido quando o host o expõe.',
    category: 'standard',
    risk: 'low',
    reversible: true,
    command: { type: 'power-plan', plan: 'auto' },
    revertCommand: { type: 'power-plan', plan: 'balanced' },
  },
  {
    id: 'clean-temp-tweak',
    name: 'Limpar temporários no preset',
    description: 'Inclui a limpeza segura (cache da app + temporários elegíveis) no pipeline de otimização.',
    category: 'standard',
    risk: 'low',
    reversible: true,
    command: { type: 'cleanup', preset: 'safe' },
    revertCommand: { type: 'noop', note: 'Ficheiros apagados não se reconstroem; o histórico guarda o que foi medido.' },
  },
  {
    id: 'telemetry-tasks',
    name: 'Desativar tarefas de telemetria conhecidas',
    description: 'Marca as tarefas agendadas de diagnóstico/CEIP como desativadas no snapshot reversível.',
    category: 'standard',
    risk: 'low',
    reversible: true,
    command: { type: 'scheduled-task', action: 'disable', group: 'telemetry' },
    revertCommand: { type: 'scheduled-task', action: 'enable', group: 'telemetry' },
  },
  {
    id: 'game-mode',
    name: 'Ativar Game Mode',
    description: 'Preferência de Game Mode do Windows — reversível, baixo risco.',
    category: 'standard',
    risk: 'low',
    reversible: true,
    command: { type: 'registry', hive: 'HKCU', path: 'Software\\Microsoft\\GameBar', value: 'AutoGameModeEnabled=1' },
    revertCommand: { type: 'registry', hive: 'HKCU', path: 'Software\\Microsoft\\GameBar', value: 'AutoGameModeEnabled=0' },
  },
  {
    id: 'menu-show-delay',
    name: 'Reduzir atraso dos menus',
    description: 'MenuShowDelay → 0. Cosmético, reversível, útil em PCs fracos.',
    category: 'standard',
    risk: 'low',
    reversible: true,
    command: { type: 'registry', hive: 'HKCU', path: 'Control Panel\\Desktop', value: 'MenuShowDelay=0' },
    revertCommand: { type: 'registry', hive: 'HKCU', path: 'Control Panel\\Desktop', value: 'MenuShowDelay=400' },
  },
  {
    id: 'end-task-taskbar',
    name: 'Terminar tarefa na barra de tarefas',
    description: 'Ativa "End Task" no menu de contexto da taskbar (equivalente ao default WinUtil Standard).',
    category: 'standard',
    risk: 'low',
    reversible: true,
    command: { type: 'registry', hive: 'HKCU', path: 'Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced\\TaskbarDeveloperSettings', value: 'TaskbarEndTask=1' },
    revertCommand: { type: 'registry', hive: 'HKCU', path: 'Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced\\TaskbarDeveloperSettings', value: 'TaskbarEndTask=0' },
  },

  // ——— Avançado ———
  {
    id: 'core-affinity',
    name: 'Afinidade de núcleos (Game Booster)',
    description: 'Reserva núcleos para o processo em foreground. Requer confirmação. Reverte ao sair do jogo.',
    category: 'advanced',
    risk: 'high',
    reversible: true,
    command: { type: 'affinity', policy: 'foreground-reserve' },
    revertCommand: { type: 'affinity', policy: 'default' },
  },
  {
    id: 'nonessential-services',
    name: 'Serviços não essenciais em Manual',
    description: 'Passa serviços da lista segura para Manual via Services Manager. Nunca toca em serviços essenciais.',
    category: 'advanced',
    risk: 'high',
    reversible: true,
    command: { type: 'service', action: 'manual', group: 'nonessential' },
    revertCommand: { type: 'service', action: 'restore', group: 'nonessential' },
  },
  {
    id: 'dynamic-tick',
    name: 'Desativar Dynamic Tick',
    description: 'bcdedit disabledynamictick. Só sugerido em PC Potente — pode aumentar consumo em portáteis.',
    category: 'advanced',
    risk: 'high',
    reversible: true,
    minTier: 'potente',
    command: { type: 'bcdedit', key: 'disabledynamictick', value: 'yes' },
    revertCommand: { type: 'bcdedit', key: 'disabledynamictick', value: 'no' },
  },
  {
    id: 'hpet',
    name: 'Ajuste HPET',
    description: 'Preferência de High Precision Event Timer. Só PC Potente; teste e reverta se houver regressão.',
    category: 'advanced',
    risk: 'high',
    reversible: true,
    minTier: 'potente',
    command: { type: 'bcdedit', key: 'useplatformclock', value: 'true' },
    revertCommand: { type: 'bcdedit', key: 'useplatformclock', value: 'delete' },
  },
  {
    id: 'network-latency',
    name: 'Tweaks de rede / latência',
    description: 'Ajusta TcpAckFrequency / Nagle para gaming. Não declara ganhos em Mbps — só aplica o perfil.',
    category: 'advanced',
    risk: 'high',
    reversible: true,
    command: { type: 'tcp', profile: 'low-latency' },
    revertCommand: { type: 'tcp', profile: 'default' },
  },
  {
    id: 'win32-priority',
    name: 'Win32PrioritySeparation',
    description: 'Favorece processos em foreground. Avançado, reversível.',
    category: 'advanced',
    risk: 'high',
    reversible: true,
    command: { type: 'registry', hive: 'HKLM', path: 'SYSTEM\\CurrentControlSet\\Control\\PriorityControl', value: 'Win32PrioritySeparation=26' },
    revertCommand: { type: 'registry', hive: 'HKLM', path: 'SYSTEM\\CurrentControlSet\\Control\\PriorityControl', value: 'Win32PrioritySeparation=2' },
  },

  // ——— Privacidade ———
  {
    id: 'diagtrack',
    name: 'Serviço de Diagnóstico (DiagTrack)',
    description: 'Diagnostic Tracking Service. Estado verificado quando o host expõe o serviço; senão, snapshot da app.',
    category: 'privacy',
    risk: 'low',
    reversible: true,
    windowsProbe: 'service:DiagTrack',
    command: { type: 'service', action: 'disable', name: 'DiagTrack' },
    revertCommand: { type: 'service', action: 'enable', name: 'DiagTrack' },
  },
  {
    id: 'telemetry-level',
    name: 'Nível de telemetria',
    description: 'AllowTelemetry → Security (0/1 conforme edição). Opt-in.',
    category: 'privacy',
    risk: 'low',
    reversible: true,
    command: { type: 'registry', hive: 'HKLM', path: 'SOFTWARE\\Policies\\Microsoft\\Windows\\DataCollection', value: 'AllowTelemetry=0' },
    revertCommand: { type: 'registry', hive: 'HKLM', path: 'SOFTWARE\\Policies\\Microsoft\\Windows\\DataCollection', value: 'AllowTelemetry=1' },
  },
  {
    id: 'advertising-id',
    name: 'ID de publicidade',
    description: 'Desativa o identificador de publicidade personalizada.',
    category: 'privacy',
    risk: 'low',
    reversible: true,
    command: { type: 'registry', hive: 'HKCU', path: 'Software\\Microsoft\\Windows\\CurrentVersion\\AdvertisingInfo', value: 'Enabled=0' },
    revertCommand: { type: 'registry', hive: 'HKCU', path: 'Software\\Microsoft\\Windows\\CurrentVersion\\AdvertisingInfo', value: 'Enabled=1' },
  },
  {
    id: 'tailored-experiences',
    name: 'Experiências personalizadas',
    description: 'Desliga insights/consumo de dados de diagnóstico para publicidade.',
    category: 'privacy',
    risk: 'low',
    reversible: true,
    command: { type: 'registry', hive: 'HKCU', path: 'Software\\Microsoft\\Windows\\CurrentVersion\\Privacy', value: 'TailoredExperiencesWithDiagnosticDataEnabled=0' },
    revertCommand: { type: 'registry', hive: 'HKCU', path: 'Software\\Microsoft\\Windows\\CurrentVersion\\Privacy', value: 'TailoredExperiencesWithDiagnosticDataEnabled=1' },
  },
  {
    id: 'location-tracking',
    name: 'Localização',
    description: 'Reduz permissões de localização ao nível de política. Abre também o painel nativo quando disponível.',
    category: 'privacy',
    risk: 'low',
    reversible: true,
    nativePanel: 'ms-settings:privacy-location',
    command: { type: 'registry', hive: 'HKLM', path: 'SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\CapabilityAccessManager\\ConsentStore\\location', value: 'Value=Deny' },
    revertCommand: { type: 'registry', hive: 'HKLM', path: 'SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\CapabilityAccessManager\\ConsentStore\\location', value: 'Value=Allow' },
  },
  {
    id: 'activity-history',
    name: 'Histórico de atividades',
    description: 'Desativa a recolha de Activity History / Timeline.',
    category: 'privacy',
    risk: 'low',
    reversible: true,
    nativePanel: 'ms-settings:privacy-activityhistory',
    command: { type: 'registry', hive: 'HKLM', path: 'SOFTWARE\\Policies\\Microsoft\\Windows\\System', value: 'PublishUserActivities=0' },
    revertCommand: { type: 'registry', hive: 'HKLM', path: 'SOFTWARE\\Policies\\Microsoft\\Windows\\System', value: 'PublishUserActivities=1' },
  },
  {
    id: 'consumer-features',
    name: 'Funções de consumidor / sugestões',
    description: 'Desativa Consumer Features (sugestões, apps sugeridas).',
    category: 'privacy',
    risk: 'low',
    reversible: true,
    command: { type: 'registry', hive: 'HKLM', path: 'SOFTWARE\\Policies\\Microsoft\\Windows\\CloudContent', value: 'DisableWindowsConsumerFeatures=1' },
    revertCommand: { type: 'registry', hive: 'HKLM', path: 'SOFTWARE\\Policies\\Microsoft\\Windows\\CloudContent', value: 'DisableWindowsConsumerFeatures=0' },
  },
  {
    id: 'wifi-sense',
    name: 'Wi-Fi Sense',
    description: 'Desativa partilha automática de redes Wi-Fi.',
    category: 'privacy',
    risk: 'low',
    reversible: true,
    command: { type: 'registry', hive: 'HKLM', path: 'SOFTWARE\\Microsoft\\WcmSvc\\wifinetworkmanager\\config', value: 'AutoConnectAllowedOEM=0' },
    revertCommand: { type: 'registry', hive: 'HKLM', path: 'SOFTWARE\\Microsoft\\WcmSvc\\wifinetworkmanager\\config', value: 'AutoConnectAllowedOEM=1' },
  },
  {
    id: 'copilot-recall',
    name: 'Copilot / Recall',
    description: 'Opt-out de recolha associada a Copilot e Recall, quando a edição as expõe.',
    category: 'privacy',
    risk: 'low',
    reversible: true,
    command: { type: 'registry', hive: 'HKCU', path: 'Software\\Policies\\Microsoft\\Windows\\WindowsCopilot', value: 'TurnOffWindowsCopilot=1' },
    revertCommand: { type: 'registry', hive: 'HKCU', path: 'Software\\Policies\\Microsoft\\Windows\\WindowsCopilot', value: 'TurnOffWindowsCopilot=0' },
  },

  // ——— Debloat (nunca essenciais) ———
  {
    id: 'debloat-xbox',
    name: 'Apps Xbox / Game Bar (não essenciais)',
    description: 'Remove pacotes UWP Xbox não essenciais. Store, Segurança e Definições nunca são tocados.',
    category: 'debloat',
    risk: 'medium',
    reversible: true,
    packages: ['Microsoft.XboxApp', 'Microsoft.XboxGamingOverlay', 'Microsoft.XboxIdentityProvider'],
    command: { type: 'appx-remove', packages: ['Microsoft.XboxApp', 'Microsoft.XboxGamingOverlay', 'Microsoft.XboxIdentityProvider'] },
    revertCommand: { type: 'appx-restore', packages: ['Microsoft.XboxApp', 'Microsoft.XboxGamingOverlay'] },
  },
  {
    id: 'debloat-bing',
    name: 'Bing / Notícias / Clima',
    description: 'Remove widgets de conteúdo Bing pré-instalados.',
    category: 'debloat',
    risk: 'medium',
    reversible: true,
    packages: ['Microsoft.BingNews', 'Microsoft.BingWeather', 'Microsoft.BingSearch'],
    command: { type: 'appx-remove', packages: ['Microsoft.BingNews', 'Microsoft.BingWeather', 'Microsoft.BingSearch'] },
    revertCommand: { type: 'appx-restore', packages: ['Microsoft.BingNews', 'Microsoft.BingWeather', 'Microsoft.BingSearch'] },
  },
  {
    id: 'debloat-solitaire',
    name: 'Solitaire Collection',
    description: 'Remove o pacote de jogos casual pré-instalado.',
    category: 'debloat',
    risk: 'medium',
    reversible: true,
    packages: ['Microsoft.MicrosoftSolitaireCollection'],
    command: { type: 'appx-remove', packages: ['Microsoft.MicrosoftSolitaireCollection'] },
    revertCommand: { type: 'appx-restore', packages: ['Microsoft.MicrosoftSolitaireCollection'] },
  },
  {
    id: 'debloat-feedback',
    name: 'Feedback Hub / Get Help',
    description: 'Remove hubs de feedback não essenciais.',
    category: 'debloat',
    risk: 'medium',
    reversible: true,
    packages: ['Microsoft.WindowsFeedbackHub', 'Microsoft.GetHelp'],
    command: { type: 'appx-remove', packages: ['Microsoft.WindowsFeedbackHub', 'Microsoft.GetHelp'] },
    revertCommand: { type: 'appx-restore', packages: ['Microsoft.WindowsFeedbackHub', 'Microsoft.GetHelp'] },
  },
  {
    id: 'debloat-onedrive',
    name: 'OneDrive (cliente de consumidor)',
    description: 'Desinstala o cliente OneDrive de consumidor. Não remove OneDrive for Business GPO. Confirmação obrigatória.',
    category: 'debloat',
    risk: 'medium',
    reversible: true,
    command: { type: 'onedrive-remove' },
    revertCommand: { type: 'onedrive-restore' },
  },
]

export const ESSENTIAL_APPS = [
  'Microsoft.WindowsStore',
  'Microsoft.Windows.Photos',
  'Microsoft.WindowsCalculator',
  'Microsoft.SecHealthUI',
  'windows.immersivecontrolpanel',
  'Microsoft.WindowsTerminal',
]

export const COMMAND_WHITELIST = new Set([
  'registry',
  'power-plan',
  'cleanup',
  'scheduled-task',
  'affinity',
  'service',
  'bcdedit',
  'tcp',
  'appx-remove',
  'appx-restore',
  'onedrive-remove',
  'onedrive-restore',
  'dns',
  'ram-trim',
  'repair',
  'noop',
])

export function getTweak(id) {
  return TWEAKS.find((t) => t.id === id)
}

export function tweaksByCategory(category) {
  return TWEAKS.filter((t) => t.category === category)
}

export function assertWhitelisted(command) {
  if (!command || !COMMAND_WHITELIST.has(command.type)) {
    throw new Error(`Comando não está na whitelist: ${command?.type}`)
  }
}
